videojs/m3u8-parser

.babelrc
package.json
src/index.js
src/parser.js

* upgrade to babel 6 to use transform-object-assign
* remove the need for lodash-merge and reduce size by ~5000kb in gzip form

Remove dependance on lodash and save lots o' bytes

---

.babelrc
package.json

It looks like the latest release of this project will break in IE8 because of `.default`, including the ES3 preset to fix that.

fix: Include the babel ES3 tranform to support IE8

---

src/parser.js
test/m3u8.test.js

If an `#EXT-X-MEDIA` for a track has a `CHARACTERISTICS` value, include that with the information about the track for use by HLS playlist playback. (possible values of `CHARACTERISTICS` include `public.accessibility.transcribes-spoken-dialog`, `public.accessibility.describes-music-and-sound`, and `public.accessibility.describes-video`).

Pass any CHARACTERISTICS value of a track with the track object

---

test/m3u8.test.js

I realized that, per the HLS standard, attribute strings need to be quoted, and wanted to make sure this works with my last change.

Small fix for attributes in characteristics test to have double-quotes

---

src/parser.js
src/utils/decode.js
test/m3u8.test.js

This adds parsing of `EXT-X-KEY` attributes for Widevine support, as outlined in this [spec](https://storage.googleapis.com/wvdocs/Widevine_DRM_HLS.pdf)

feat: parse key attributes for Widevine HLS

---

src/parser.js
test/fixtures/m3u8/byteRange.json
test/m3u8.test.js

The default value for EXT-X-BYTERANGE is defined by the spec as the first byte
after the previous segment. Prior to this change, the default set by m3u8-parser
was 0.

Fix default EXT-X-BYTERANGE offset to start after the previous segment

---

src/parse-stream.js
src/parser.js
test/fixtures/m3u8/llhlsDelta.json

This pull request adds support for the `#EXT-X-SKIP` tag and all of the attributes currently in the specification for it.
See:
* https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls#3282433
* https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.5.2

feat: add support for #EXT-X-SKIP

---

src/parse-stream.js
src/parser.js
test/fixtures/m3u8/llhls.json
test/fixtures/m3u8/llhlsDelta.json

This pull request adds support for the `#EXT-X-PRELOAD-HINT` tag and all of the attributes currently in the specification for it.
See:
* https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls#3526694
* https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.5.3

feat: add support for #EXT-X-PRELOAD-HINT

---

src/parse-stream.js
src/parser.js
test/fixtures/m3u8/llhls.json
test/fixtures/m3u8/llhlsDelta.json

This pull request adds support for the `#EXT-X-SERVER-CONTROL` tag and all of the attributes currently in the specification for it.
See:
* https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls#3281374
* https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.3.8

feat: add support for #EXT-X-SERVER-CONTROL

---

src/parse-stream.js
src/parser.js
test/fixtures/m3u8/llhls.json
test/fixtures/m3u8/llhlsDelta.json

This pull request adds support for the `#EXT-X-RENDITION-REPORT` tag and all of the attributes currently in the specification for it.
See:
* https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls#3282435
* https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.5.4

feat: add support for #EXT-X-RENDITION-REPORT

---

src/parse-stream.js
src/parser.js
test/fixtures/m3u8/llhls.json
test/fixtures/m3u8/llhlsDelta.json

This pull request adds support for the `#EXT-X-PART-INF` tag and all of the attributes currently in the specification for it.
See:
* https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls#3282434
* https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08#section-4.4.3.7

feat: add support for #EXT-X-PART-INF

---

src/parser.js
test/fixtures/integration/allowCache.js
test/fixtures/integration/allowCacheInvalid.js
test/fixtures/integration/byteRange.js
test/fixtures/integration/disallowCache.js
test/fixtures/integration/disc-sequence.js
test/fixtures/integration/discontinuity.js
test/fixtures/integration/emptyAllowCache.js
test/fixtures/integration/encrypted.js
test/fixtures/integration/extinf.js
test/fixtures/integration/fmp4.js
test/fixtures/integration/invalidAllowCache.js
test/fixtures/integration/invalidTargetDuration.js
test/fixtures/integration/llhls.js
test/fixtures/integration/llhlsDelta.js
test/fixtures/integration/master-fmp4.js
test/fixtures/integration/missingExtinf.js
test/fixtures/integration/playlist.js
test/fixtures/integration/start.js

We never used the `#EXT-X-VERSION` even though we parsed it. `totalduration` doesn't exist in parse-stream and there isn't anything equivalent in the spec.

feat: add version parsing and remove totalduration

---

src/parser.js
test/parser.test.js

fix: ignore fairplay content protection

---

src/parse-stream.js
test/fixtures/integration/master-fmp4.js

The 'FRAME-RATE' attribute should be a floating-point number type rather than a string.

feat: improve parsing for a frame-rate attribute

---

src/parse-stream.js
test/parse-stream.test.js
test/parser.test.js

Fixes #22 
Brings in changes from PR #50 to a present-day base.
This might be considered a breaking change as the library will no longer tolerate missing `:` tag delimiter.

fix: non standard tag match

---

README.md
src/parse-stream.js
src/parser.js
test/fixtures/integration/fmp4.js
test/fixtures/integration/master-fmp4.js
test/parse-stream.test.js
test/parser.test.js

Add support for parsing [#EXT-X-INDEPENDENT-SEGMENTS](http://tools.ietf.org/html/draft-pantos-http-live-streaming#section-4.3.5.1) tags.

feat: add independent-segments support

---

README.md
src/parser.js
test/fixtures/integration/disc-sequence.js
test/fixtures/integration/discontinuity.js
test/fixtures/integration/emptyMediaSequence.js
test/fixtures/integration/extXPlaylistTypeInvalidPlaylist.js
test/fixtures/integration/extinf.js
test/fixtures/integration/invalidMediaSequence.js
test/fixtures/integration/liveMissingSegmentDuration.js
test/fixtures/integration/liveStart30sBefore.js
test/fixtures/integration/mediaSequence.js
test/fixtures/integration/missingMediaSequence.js
test/fixtures/integration/missingSegmentDuration.js
test/fixtures/integration/negativeMediaSequence.js
test/fixtures/integration/playlistMediaSequenceHigher.js
test/fixtures/integration/twoMediaSequences.js

Currently segment titles are parsed but not returned.
Close #90

Output segment title from EXTINF

---

src/parser.js

`Parser.addParser` is a pass through to `ParseStream.addParser`, which uses and
documents `customType`. The same is in public docs (README)
Thanks!

docs: correct `customType` option name

---

README.md
src/parse-stream.js
src/parser.js
test/fixtures/integration/dateTime.js
test/fixtures/integration/llhls.js
test/fixtures/integration/llhlsDelta.js
test/parse-stream.test.js

Adds `dateTimeObject` and `dateTimeString` back as segment and manifest properties.

fix: add dateTimeObject and dateTimeString for backward compatibility

---

src/parse-stream.js
src/parser.js
test/parse-stream.test.js
test/parser.test.js

Add support for parsing `#EXT-X-CONTENT-STEERING` tags, required `SERVER-URI` property and associated `PATHWAY-ID` attributes.
https://developer.apple.com/streaming/HLSContentSteeringSpecification.pdf
https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.6

feat: parse content steering tags and attributes

---

README.md

Add the now supported main manifest tag `EXT-X-CONTENT-STEERING` to the README.md

chore: add content-steering tag to readme
